#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend alxrob.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 420208-web-01 54.237.1.142 check
        server 420208-web-02 52.91.132.134 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
