#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

sudo apt-get update

# installing a dedicated PPA
sudo apt-get install -ysoftware-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.6

# Install HAproxy on a server
sudo pt-get -y update
sudo apt-get -y install haproxy=2.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend alxrob.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 420208-web-01 54.237.1.142 check
        server 420208-web-02 52.91.132.134 check
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
sudo systemctl status haproxy.service
