#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# a custom header

ha_proxy_balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 420208-web-01 54.237.1.142:80 check
    server 420208-web-02 52.91.132.134:80 check
"
# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$ha_proxy_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
